-- Delete old users table if exist
DROP TABLE IF EXISTS users;
-- Create Users Table
CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT, 
	name VARCHAR(50) NOT NULL UNIQUE, 
	password VARCHAR(50) NOT NULL, 
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS products;
CREATE TABLE products(
	id INT NOT NULL AUTO_INCREMENT, 
	name VARCHAR(50) NOT NULL UNIQUE, 
	price INT DEFAULT 0,
	qty INT DEFAULT 0,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS orders;
CREATE TABLE orders(
	id INT NOT NULL AUTO_INCREMENT, 
	user_id INT NOT NULL,
	product_id INT NOT NULL,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (product_id) REFERENCES products(id)
);
